try {
    console.aula('This is an error');
} catch (error) {
    console.log('Do anything here');
    // console.log(error);
}